# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171105_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_img',
            field=models.CharField(default='https://images.unsplash.com/photo-1507834251994-9191f78e15ac?auto=format&fit=crop&w=1936&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='article_subheading',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
