# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20171114_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
